`tag` pneumaticcraft:pressurable
EnigmaticaModpacks/Enigmatica6 pull request #4973
Opened 2022-06-08 11:02 UTC by Quezler

Somehow this does not show up in `./kubejs/exported/tags/items.txt`, so there's probably still a mistake somewhere. 🤔 

I could really use this tag for computercraft, being able to export items that can be charged in a charging station without having to hardcode this same list inside lua.

Logs for the ci run can be found [here](https://github.com/Quezler/Enigmatica6/actions/runs/2460895345), but i could not spot any kubejs errors related to why this tag might not be working.

2022-06-08 14:11 UTC, Quezler commented
Fine by me, will move it there once i figure out why it isn't working as-is 🤔

2022-06-08 15:10 UTC, Quezler commented
looks like it works, but i guess i will have to fix the regexes since more stuff made it in than anticipated:
![Screen Shot 2022-06-08 at 17 09 45](https://user-images.githubusercontent.com/3179271/172652252-1f36a9f8-b195-4f7c-9adf-87d2467173b5.png)

2022-06-08 17:21 UTC, Quezler commented
I was only looking `#pressure` in jei at the time and noticed some of the pressurized items shared the `pneumaticcraft:pressure_` prefix, didn't test it at the time since i was working on something else and didn't want to reboot that instance just yet, which is why i had set this to draft mode since it wasn't properly tested/working, a harmless oversight.

2022-06-09 16:10 UTC, Quezler commented
Decided to hijack this in order to include ci that can compare changes in tags: 
![Screen Shot 2022-06-09 at 18 07 27](https://user-images.githubusercontent.com/3179271/172893900-ac2c70ff-2922-42cf-8c62-4b9ff827ea24.png)

Clicking it will give a nice git-like diff of the changes:
![Screen Shot 2022-06-09 at 18 07 39](https://user-images.githubusercontent.com/3179271/172893999-28fefb84-01ad-4c06-8358-5513d4af1891.png)

2022-06-09 16:29 UTC, Quezler commented
when searching `#pressure` in jei:
![Screen Shot 2022-06-09 at 18 21 38](https://user-images.githubusercontent.com/3179271/172896475-e7c50bc9-d4c8-4f59-9868-79f2aa34b84a.png)

when searching `$storage/air` in jei:
![Screen Shot 2022-06-09 at 18 22 01](https://user-images.githubusercontent.com/3179271/172896548-9a1ef093-dfdd-4b8a-93ef-54fb17ade5a2.png)

new tags under `forge:storage/air`:
![Screen Shot 2022-06-09 at 18 27 42](https://user-images.githubusercontent.com/3179271/172897471-5e75e689-72d4-474b-ba10-97d99a111e2d.png)

new tags under `forge:storage`:
![Screen Shot 2022-06-09 at 18 28 35](https://user-images.githubusercontent.com/3179271/172897596-fd4c5109-95a6-45f4-8c17-9cedbbbe455d.png)

2022-06-09 16:47 UTC, Quezler commented
@NielsPilgaard ready for review 🍿

2022-06-09 17:38 UTC, NielsPilgaard requested changes
I think the tags are a fine addition, I think the CI additions are cool but overkill to be honest, I'd rather not have those.

2022-06-09 17:38 UTC, NielsPilgaard commented on kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/air.js
> +  var tags = ['forge:storage', 'forge:storage/air'];
I recommend you use `const` here.

2022-06-09 18:05 UTC, Quezler commented
> I think the tags are a fine addition, I think the CI additions are cool but overkill to be honest, I'd rather not have those.

After working on getting ci to work for pull requests + being able to compare against the pull request i did not expect this.

My other (accepted) ci pull requests were all about making computed data accessible (aka: stuff not visible in the kubejs json files alone), like: counting recipes, finding out which recipes use randomized ids, finding any startup errors, etc.

Therefore it seemed reasonable to me that showing a diff for changed tags made sense, sure they are configured inside the kubejs json files, but you won't know the result until after kubejs has had a run and exported the final tags.

For string arrays of tags the value is indeed minimal since it is 1:1, but any time regex item matches are involved it serves as a valuable check to see if all the items you want it to match are matching, as well as detecting ones that should not make it.

It also serves as a sort of test, if in the future the tag code gets refactored (with the intention of updating just the code, not changing anything) this will be able to verify if nothing has truly changed as far as kubejs is concerned.

Are you absolutely sure you want me to strip out the entire ci part? not to mention future avenues of comparing branches 🤔

2022-06-09 20:06 UTC, NielsPilgaard approved these changes

2022-06-09 20:09 UTC, NielsPilgaard commented
The thing is, I don't like to have code running in our actions that I don't fully understand. I don't have the time to learn, I barely have the time to read it. I cannot maintain this, nor do I want to.

That being said, sure, I'll merge this one, I can see the benefit of it.

2022-06-09 20:09 UTC, merged

2022-06-09 20:13 UTC, Quezler commented
i'll add some more comments to this tomorrow if you'd like 🤔 

also the ci is not part of the deployment process, if something breaks and for whatever reason i am not around, it can be uncommented/discarded just fine 😇

2022-06-09 20:38 UTC, NielsPilgaard commented
No thank you. I rarely have more than 20 minutes per day for Minecraft development, I do not want to spend it reading code comments for CI, no offense :P