Added jei description for sulfur and sulfur dust
EnigmaticaModpacks/Enigmatica6 pull request #5064
Opened 2022-07-07 09:41 UTC by Gcat101

A lot of newcomers think making sulfur dust requires mekanism and other late-game mods, when really it doesn't. I added a jei description so people would stop asking the same question over and over on discord.

2022-07-07 10:51 UTC, NielsPilgaard requested changes
Nice addition, thank you for your contribution :D

2022-07-07 10:51 UTC, NielsPilgaard commented on kubejs/client_scripts/item_modifiers/jei_descriptions.js
> +            text: [`Sulfur ore isn't obtainable in this modpack. Check out the recipe for the Farmer's Delight's cooking pot.`]
I'd like `Sulfur ore` to be `Sulfur Ore`

2022-07-07 10:55 UTC, MuteTiefling requested changes
Sulfur Ore is obtainable, however, just not directly from mining. So that should be clarified. 

Also, the Farmer's Delight recipe is unique to Expert. So putting this as a JEI description for both modes is confusing. It should more generically point people to look at recipes for Sulfur Dust.

2022-07-07 11:21 UTC, Quezler commented
they likely meant the `jei_decriptions.js` in the expert subdirectory so it only loads in that mode, instead of mentioning in the text for both modes that its only for expert: https://github.com/EnigmaticaModpacks/Enigmatica6/blob/develop/kubejs/client_scripts/expert/item_modifiers/jei_descriptions.js

2022-07-07 11:24 UTC, Gcat101 commented
yeah I'm just dumb

2022-07-07 13:04 UTC, MuteTiefling commented
Nah, I just meant making a more generic message that works for both. There's nothing drastic about the Expert recipes. For both modes, a simple reminder to look at the recipes for Sulfur Dust is sufficient.

2022-07-07 14:47 UTC, MuteTiefling commented
We've generally only used this type of description to explain things that are otherwise not discoverable in game, like the recent descriptions added to brewing. The only way to know how to craft those is pure trial and error, or checking an external wiki.

This isn't a case like that. The recipe is plainly visible in JEI. If they aren't seeing it, they're also going to miss this description. 

A quest would make more sense, but that feels very hand-holdy for an Expert pack.

2022-07-07 15:14 UTC, Gcat101 commented
whoop commit duplication

2022-07-22 13:05 UTC, Gcat101 commented
Closing this since it seems there’s no progress being made

2022-07-22 13:05 UTC, closed without merging

2022-07-22 16:19 UTC, NielsPilgaard commented
We were expecting you to make the changes to be honest, since you said Ok Sure, that's how pull request development usually goes :D

2022-07-22 16:33 UTC, Gcat101 commented
Yeah I know but there were no comments for 15 days so I closed it

2022-07-22 16:36 UTC, Gcat101 commented
Should've just made a new branch. I'm a moron.

2022-07-22 17:51 UTC, NielsPilgaard commented
Fair enough 👍 

... I don't think you're a moron though 😅